### ISSUE TITLE
assign_rsid

### ISSUE THREAD

**Issue by MC4R** [Cloufield/gwaslab#123]
Hi He,

Hope all is well.

I am assigning rsIDs to a GWAS dataset (build 38) using the `mysumstats.assign_rsid` function. After loading the GWAS data, I performed QC checks with `mysumstats.basic_check()` before running `mysumstats.assign_rsid`. The dataset contains 8,710,726 rows, but only 736,026 were successfully mapped to rsIDs.

Here is the code that I am using

```
mysumstats.assign_rsid( 
...                         ref_rsid_tsv = gl.get_path("1kg_dbsnp151_hg38_auto"),
...                         chr_dict = gl.get_number_to_NC(build="38"),
...                         n_cores = 2)
```
<img width="1329" alt="Screenshot 2024-12-18 at 11 20 38" src="https://github.com/user-attachments/assets/fc7ed093-c62f-4eb9-8589-3b328a918423" />

Any thoughts on why so many rows are being skipped during the rsID assignment?

Thank you.
Dev

**Comment by Cloufield** [comment]
Hi Dev,

Based on the log, it seems that 7,974,700 variants were annotated with rsID successfully and only 736,026 (<10%?) were not annotated, which needs to be fixed by other sources. 

`assign_rsid` with the SNPID-rsID table are conducted completely based on SNPID, which should be in the format of CHR:POS:REF:ALT. And this table only contains autosomal variants from 1kg datasets. To maxmize the number of variants that can be annotated with rsID, after assigning rsID with the SNPID-rsID table, you could also use the dbSNP vcf file.

Here is an example:
https://cloufield.github.io/gwaslab/tutorial_3.4/#maximize-the-annotation

**Comment by Cloufield** [comment]
Hi Dev,

`mysumstats.basic_check()` will not check for alignment, and neither will `mysumstats.assign_rsid()` .

Instead, `mysumstats.harmonize()` is specifically designed for this. 
It will check the alignment, flip the alleles and change statistics accordingly. 

You could try this if you need to check that:
```
mysumstats.harmonize(basic_check=False,
                     n_cores=2,
                     ref_seq = "your_path_to_hg38.fasta"
```

https://cloufield.github.io/gwaslab/tutorial_3.4/#harmonization

**Comment by MC4R** [comment]
Hi He,

This is very helpful. Thank you so much for this wonderful package.

Bw,
Dev
