### ISSUE TITLE
Questions re assigning rsID and liftover

### ISSUE THREAD

**Issue by XcodeBio** [Cloufield/gwaslab#125]
Hi He,

How are you?

I have a couple of questions regarding assigning rsIDs and liftover. 

1. rsID assign using `mysumstats.assign_rsid`: does it matter whether the input data is in CHR:POS:NEA:EA or CHR:POS:EA:NEA format? I am asking this as the following page says "For TSV file, variants will be matched using SNPID (CHR:POS:NEA:EA) for quick assigning: https://cloufield.github.io/gwaslab/Harmonization/

2. Liftover: I lifted over data (build 19 >> build 38) with the following command and I got two types of code in the 'STATUS' column. Majority of rows have `3860999` but some of the rows have `3880999` code. It seems to me that the programme could not lift over rows with 3880999. Is it safe to exclude these rows from any downstream analysis or is there any other way to map these to build 38?
`mysumstats.liftover(n_cores=2, from_build="19", to_build="38",chain="hg19ToHg38.over.chain.gz")`

Thank you for your time and help with this.

Bw,
Dev

**Comment by Cloufield** [comment]
Hi Dev,
Sorry for my late reply.
1. SNPID should be in CHR:POS:REF:ALT (or CHR:POS:NEA:EA if NEA is aligned with REF) format if you are using the TSV since gwaslab only use the SNPID to merge with the reference table. If using VCF, either format is ok.
2. Could you please show some examples of vairants with `3880999`. This code suggests that the rsID and SNPID are not valid. I am wondernig if this is what you observed? `3860999` means that rsID is invalid but SNPID is valid.

**Comment by XcodeBio** [comment]
Hi He,

Many thanks for your reply. 

1. My GWAS data is in  CHR:POS:EA:NEA format. Does it mean that it can not be used to assign rsIDs correctly? I actually used both CHR:POS:EA:NEA and CHR:POS:NEA:EA with `mysumstats.assign_rsid` and it gave me similar results. I am using both tsv and vcd files and here is the command
```
datamysumstats.assign_rsid( 
                        ref_rsid_tsv = gl.get_path("1kg_dbsnp151_hg19_auto"),
                        ref_rsid_vcf = "GCF_000001405.25.gz",
                        chr_dict = gl.get_number_to_NC(build="19"),
                        n_cores = 5)
```
Also, could `mysumstats.assign_rsid` be used with CHR:POS only?

2. I noticed that all rows with `3880999` code have either CN2 or CN0 in the SNP ID column. I could not find the page listing these codes.
3. Could I use CHR:POS as SNPID for liftover?

Thank you very much.

**Comment by Cloufield** [comment]
Hi,
1. Since you used both tsv and VCF files, gwaslab will first use the tsv to assign rsID based on CHR:POS:REF:ALT and then use VCF to  assign rsID based on CHR,POS,REF,ALT (it also works if REF/ALT are flipped). That is why you get similar results. And yes, you can use it with CHR:POS only, but it only works with VCF.
2. Here is the page: https://cloufield.github.io/gwaslab/StatusCode/
3. Yes, but be sure to run basic_check() to check your sumstats first. The chain file is for liftover from hg38 to hg19.
