### ISSUE TITLE
python version dependencies

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#77]
Dear Yunye,

Is there a gwaslab version with loose the version of python dependencies. I want to use it in a multi-site project, while the specific python version requirements seem not friendly for some people.

Best, Chenyang

**Comment by Cloufield** [comment]
Hi Chenyang,

If it is just python version, you can try `pip install --ignore-requires-python gwaslab` since gwaslab may work with other python versions but I haven't tested yet. You can test if it works in your pipeline.

If the confilct is caused by some packages, would you please let me know which package exactly?  Thanks. 

FYI, Current requirments:
```
dependencies = [
    "pandas>=1.3,!=1.5",
    "numpy>=1.21.2",
    "matplotlib>=3.5,!=3.7.2",
    "seaborn>=0.12",
    "scipy>=1.12",
    "pySAM>=0.18.1,<0.20",
    "Biopython>=1.79",
    "adjustText>=0.7.3, <=0.8",
    "liftover>=1.1.13",
    "scikit-allel>=1.3.5",
    "pyensembl==2.2.3",
    "gtfparse==1.3.0"
]

requires-python = ">=3.9,<=3.10"
```
